let userName = prompt("Как тебя зовут?")
console.log(userName)
alert("Добро пожаловать, " + userName + "!"+ " Рады видеть тебя.")
let task_1 = prompt("Готов пройти наш опрос?")
alert("Ты ответил(а) "+ task_1 + ".")
let task_2 = prompt("Мы всё равно его проведем. Сколько тебе лет?")
console.log(task_2)
alert("Тебе "+task_2+" лет. Отлично.")
let task_3 = prompt("Из какого ты города?")
console.log(task_3)
let task_4 = prompt("Напиши твою самую характерную черту.")
console.log(task_4)
let task_5 = prompt("Какой твой любимый цвет?")
console.log(task_5)
alert("Да, "+task_5+" - красивый цвет.")
let task_6 = prompt("Что ты больше всего ненавидишь?")
console.log(task_6)
alert("Иу, "+task_6+" невозможно любить.")
let task_7 = prompt("Какой способностью тебе хотелось бы обладать?")
console.log(task_7)
alert("Да, "+task_7+" - крутая способность.")
let task_8 = prompt("Чего ты боишься?")
console.log(task_8)
alert("Это страшно.")
let task_9 = prompt("Любимое время года?")
console.log(task_9)
let task_10 = prompt("На сколько баллов из 10 оценишь этот опрос?")
console.log(task_10)
alert("Спасибо за оценку. "+task_10+" - это отличный результат.")